[throttling]
close_radius = 16.0
medium_radius = 64.0
close_rate = 1.0
medium_rate = 0.3
far_rate = 0.1

[item_optimization]
max_items_per_chunk = 50
despawn_time_seconds = 150
merge_enabled = true

[ai_optimization]
passive_disable_distance = 32.0
hostile_simplify_distance = 64.0
ai_tick_rate_far = 0.1

[logging]
level = "error"

[metrics]
export_prometheus = false
prometheus_port = 9090

[performance]
# Ultra-performance settings
enable_aggressive_optimizations = true
max_concurrent_operations = 32
batch_size = 64
prefetch_distance = 8
cache_size_mb = 512

[compatibility]
# Automatically disable features if conflicting mods are detected
disable_tick_optimization_if_lithium = true
disable_item_optimization_if_ferritecore = false
disable_ai_optimization_if_starlight = false

[exceptions]
# Entity types that should not be optimized (e.g., boss entities, critical machines)
critical_entity_types = ["minecraft:wither", "minecraft:ender_dragon"]

[ultra_optimizations]
# Disable expensive safety checks
enable_safety_checks = false
enable_bounds_checking = false
enable_null_checks = false

# Enable aggressive inlining
enable_aggressive_inlining = true

# Enable loop unrolling
enable_loop_unrolling = true

# Enable vectorization optimizations
enable_vectorization = true

# Enable memory pooling
enable_memory_pooling = true
pool_size_mb = 256

# Enable SIMD optimizations
enable_simd = true
simd_batch_size = 16

# Enable branch prediction hints
enable_branch_hints = true

# Enable cache prefetching
enable_cache_prefetching = true