// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;


use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod kneaf {

  use core::mem;
  use core::cmp::Ordering;

  
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod entity {

  use core::mem;
  use core::cmp::Ordering;

  
  use self::flatbuffers::{EndianScalar, Follow};

pub enum EntityDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EntityData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EntityData<'a> {
  type Inner = EntityData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EntityData<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_KIND: flatbuffers::VOffsetT = 6;
  pub const VT_ACTIVE: flatbuffers::VOffsetT = 8;
  pub const VT_POS_X: flatbuffers::VOffsetT = 10;
  pub const VT_POS_Y: flatbuffers::VOffsetT = 12;
  pub const VT_POS_Z: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EntityData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args EntityDataArgs<'args>
  ) -> flatbuffers::WIPOffset<EntityData<'bldr>> {
    let mut builder = EntityDataBuilder::new(_fbb);
    builder.add_id(args.id);
    builder.add_pos_z(args.pos_z);
    builder.add_pos_y(args.pos_y);
    builder.add_pos_x(args.pos_x);
    builder.add_active(args.active);
    if let Some(x) = args.kind { builder.add_kind(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    unsafe { self._tab.get::<u64>(EntityData::VT_ID, Some(0)).unwrap() }
  }
  #[inline]
  pub fn kind(&self) -> Option<&'a str> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(EntityData::VT_KIND, None) }
  }
  #[inline]
  pub fn active(&self) -> u8 {
    unsafe { self._tab.get::<u8>(EntityData::VT_ACTIVE, Some(0)).unwrap() }
  }
  #[inline]
  pub fn pos_x(&self) -> f32 {
    unsafe { self._tab.get::<f32>(EntityData::VT_POS_X, Some(0.0)).unwrap() }
  }
  #[inline]
  pub fn pos_y(&self) -> f32 {
    unsafe { self._tab.get::<f32>(EntityData::VT_POS_Y, Some(0.0)).unwrap() }
  }
  #[inline]
  pub fn pos_z(&self) -> f32 {
    unsafe { self._tab.get::<f32>(EntityData::VT_POS_Z, Some(0.0)).unwrap() }
  }
}

impl flatbuffers::Verifiable for EntityData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("kind", Self::VT_KIND, false)?
     .visit_field::<u8>("active", Self::VT_ACTIVE, false)?
     .visit_field::<f32>("pos_x", Self::VT_POS_X, false)?
     .visit_field::<f32>("pos_y", Self::VT_POS_Y, false)?
     .visit_field::<f32>("pos_z", Self::VT_POS_Z, false)?
     .finish();
    Ok(())
  }
}
pub struct EntityDataArgs<'a> {
    pub id: u64,
    pub kind: Option<flatbuffers::WIPOffset<&'a str>>,
    pub active: u8,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
}
impl<'a> Default for EntityDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntityDataArgs {
      id: 0,
      kind: None,
      active: 0,
      pos_x: 0.0,
      pos_y: 0.0,
      pos_z: 0.0,
    }
  }
}

pub struct EntityDataBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> EntityDataBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(EntityData::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EntityData::VT_KIND, kind);
  }
  #[inline]
  pub fn add_active(&mut self, active: u8) {
    self.fbb_.push_slot::<u8>(EntityData::VT_ACTIVE, active, 0);
  }
  #[inline]
  pub fn add_pos_x(&mut self, pos_x: f32) {
    self.fbb_.push_slot::<f32>(EntityData::VT_POS_X, pos_x, 0.0);
  }
  #[inline]
  pub fn add_pos_y(&mut self, pos_y: f32) {
    self.fbb_.push_slot::<f32>(EntityData::VT_POS_Y, pos_y, 0.0);
  }
  #[inline]
  pub fn add_pos_z(&mut self, pos_z: f32) {
    self.fbb_.push_slot::<f32>(EntityData::VT_POS_Z, pos_z, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> EntityDataBuilder<'a, 'b> {
    let start = _fbb.start_table();
    EntityDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EntityData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EntityData<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EntityData");
      ds.field("id", &self.id());
      ds.field("kind", &self.kind());
      ds.field("active", &self.active());
      ds.field("pos_x", &self.pos_x());
      ds.field("pos_y", &self.pos_y());
      ds.field("pos_z", &self.pos_z());
      ds.finish()
  }
}

... (truncated for brevity) ...
