// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;


use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod kneaf {

  use core::mem;
  use core::cmp::Ordering;

  
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod mob {

  use core::mem;
  use core::cmp::Ordering;

  
  use self::flatbuffers::{EndianScalar, Follow};

pub enum MobEntityDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MobEntityData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MobEntityData<'a> {
  type Inner = MobEntityData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> MobEntityData<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_TYPE: flatbuffers::VOffsetT = 6;
  pub const VT_X: flatbuffers::VOffsetT = 8;
  pub const VT_Y: flatbuffers::VOffsetT = 10;
  pub const VT_Z: flatbuffers::VOffsetT = 12;
  pub const VT_DISTANCE: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MobEntityData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args MobEntityDataArgs<'args>
  ) -> flatbuffers::WIPOffset<MobEntityData<'bldr>> {
    let mut builder = MobEntityDataBuilder::new(_fbb);
    builder.add_id(args.id);
    builder.add_distance(args.distance);
    builder.add_z(args.z);
    builder.add_y(args.y);
    builder.add_x(args.x);
    if let Some(x) = args.r#type { builder.add_r#type(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    unsafe { self._tab.get::<u64>(MobEntityData::VT_ID, Some(0)).unwrap() }
  }
  #[inline]
  pub fn r#type(&self) -> Option<&'a str> {
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MobEntityData::VT_TYPE, None) }
  }
  #[inline]
  pub fn x(&self) -> i32 {
    unsafe { self._tab.get::<i32>(MobEntityData::VT_X, Some(0)).unwrap() }
  }
  #[inline]
  pub fn y(&self) -> i32 {
    unsafe { self._tab.get::<i32>(MobEntityData::VT_Y, Some(0)).unwrap() }
  }
  #[inline]
  pub fn z(&self) -> i32 {
    unsafe { self._tab.get::<i32>(MobEntityData::VT_Z, Some(0)).unwrap() }
  }
  #[inline]
  pub fn distance(&self) -> f32 {
    unsafe { self._tab.get::<f32>(MobEntityData::VT_DISTANCE, Some(0.0)).unwrap() }
  }
}

impl flatbuffers::Verifiable for MobEntityData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("type", Self::VT_TYPE, false)?
     .visit_field::<i32>("x", Self::VT_X, false)?
     .visit_field::<i32>("y", Self::VT_Y, false)?
     .visit_field::<i32>("z", Self::VT_Z, false)?
     .visit_field::<f32>("distance", Self::VT_DISTANCE, false)?
     .finish();
    Ok(())
  }
}
pub struct MobEntityDataArgs<'a> {
    pub id: u64,
    pub r#type: Option<flatbuffers::WIPOffset<&'a str>>,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub distance: f32,
}
impl<'a> Default for MobEntityDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    MobEntityDataArgs {
      id: 0,
      r#type: None,
      x: 0,
      y: 0,
      z: 0,
      distance: 0.0,
    }
  }
}

pub struct MobEntityDataBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MobEntityDataBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(MobEntityData::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_r#type(&mut self, r#type: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MobEntityData::VT_TYPE, r#type);
  }
  #[inline]
  pub fn add_x(&mut self, x: i32) {
    self.fbb_.push_slot::<i32>(MobEntityData::VT_X, x, 0);
  }
  #[inline]
  pub fn add_y(&mut self, y: i32) {
    self.fbb_.push_slot::<i32>(MobEntityData::VT_Y, y, 0);
  }
  #[inline]
  pub fn add_z(&mut self, z: i32) {
    self.fbb_.push_slot::<i32>(MobEntityData::VT_Z, z, 0);
  }
  #[inline]
  pub fn add_distance(&mut self, distance: f32) {
    self.fbb_.push_slot::<f32>(MobEntityData::VT_DISTANCE, distance, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MobEntityDataBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MobEntityDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MobEntityData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MobEntityData<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MobEntityData");
      ds.field("id", &self.id());
      ds.field("type", &self.r#type());
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.field("distance", &self.distance());
      ds.finish()
  }
}

... (truncated for brevity) ...
