[package]
name = "rustperf"
version = "0.1.0"
edition = "2021"

[features]
jni = []

[lib]
name = "rustperf"
crate-type = ["cdylib", "rlib"]

[dependencies]
j4rs = "0.17"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.19"
serde_json = "1.0"
jni = "0.21"
lazy_static = "1.4"
sysinfo = "0.30"
rayon = "1.8"
bevy_reflect = "0.14"
bevy_ecs = "0.14"
glam = "0.27"
nalgebra = "0.32"
ndarray = "0.15"
memmap2 = "0.5"
crossbeam = "0.8"
crossbeam-channel = "0.5"
dashmap = "5.5"
blake3 = "1.3"
log = "0.4"
env_logger = "0.10"
sled = "0.34"
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.16"
fastrand = "2.0"
byteorder = "1.4"
fastnbt = "2.6"

[target.'cfg(not(target_os = "windows"))'.dependencies]
mimalloc = "0.1"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"
