[package]
name = "rustperf"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustperf"
crate-type = ["cdylib", "rlib"]

[dependencies]
j4rs = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jni = "0.21"
lazy_static = "1.4"
sysinfo = "0.30"
rayon = "1.8"
bevy_reflect = "0.14"
bevy_ecs = "0.14"
glam = "0.27"

[dev-dependencies]
