[package]
name = "rustperf"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustperf"
crate-type = ["cdylib", "rlib"]

[dependencies]
j4rs = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
jni = "0.21"
lazy_static = "1.4"
sysinfo = "0.30"
rayon = "1.8"
valence = { git = "https://github.com/valence-rs/valence" }
bevy_reflect = "0.14"

[dev-dependencies]
criterion = "0.5"
bevy_ecs = "0.14"
bevy_reflect = "0.14"

[[bench]]
name = "performance_benchmarks"
harness = false
